### ISSUE TITLE
私有部署 Gitlab CI/CD  Docker实践

### ISSUE THREAD

**Issue by Xxxdxs** [Xxxdxs/blog#18]
## 准备工作
1. 虚拟机 windows自带hyper-v
2. 系统 ubuntu20.04 

内存分配5G+ 硬盘15G+ 否则不够用, gitlab会很吃内存. 之前在我2G的小鸡上跑, 连ssh都登陆不上了, 所以安装在本地.

hyper-v安装ubuntu20.04后, 剪贴板不能正常工作, 所以安装个ssh, 在win10上远程登陆操作. 

```shell
// 查看ip
sudo apt install net-tools
ifconfig

// 安装ssh
sudo apt update
sudo apt install openssh-server
```

ssh登陆
```shell
ssh user@ip 
```

## 安装docker docker-compose
安装官方文档即可

### 安装docker
```shell
 sudo apt-get update
 
 sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
    
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
 
 echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io

// 安装成功
sudo docker run hello-world // Hello from Docker! ....
  
```

### 安装docker-compose
使用 docker-compose 可以轻松高效地管理容器, 它是一个用于定义和运行多容器 Docker 的应用程序工具.

```shell
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

// 添加执行权限
sudo chmod +x /usr/local/bin/docker-compose

// 添加软连接
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

// 验证安装
docker-compose --version // docker-compose version 1.29.2
```

## docker安装gitlab和gitlab-runner

```shell
sudo docker pull gitlab/gitlab-ce
sudo docker pull gitlab/gitlab-runner

docker images // 验证镜像拉取成功
```

## docker-compose 启动容器

新建一个 docker-compose.yml
```yml
gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'your host ip'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://your host ip'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '7443:443'
  volumes:
    - '/data/gitlab/config:/etc/gitlab'
    - '/data/gitlab/logs:/var/log/gitlab'
    - '/data/gitlab/data:/var/opt/gitlab'

gitlab-runner:
  image: gitlab/gitlab-runner
  restart: unless-stopped
  privileged: true
  volumes:
    - /data/runner/gitlab-runner:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/bin/docker
```

后台启动docker-compose 

```shell
sudo docker-compose up -d
```
等待gitlab启动, 访问ip地址: 

![image.png](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/5388a0ec18e04a36a671e99c96890e81~tplv-k3u1fbpfcp-watermark.image)

成功!

### 修改登陆gitlab的root密码
gitlab默认注册账号需要管理员通过才能使用

查看docker containerid, 进入容器

```shell
sudo docker ps 

sudo docker exec -it container_id bash
```

进入容器后
```shell
cd /opt/gitlab/bin/

gitlab-rails console

user = User.where(id: 1).first
user.password = 'your pwd'
user.password_confirmation = 'your pwd'
user.save // true
```

用刚才修改的密码登陆gitlab

新建一个空仓库, 注册gitlab-runner

![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f774f2835f654866b2b88fcb24a220ef~tplv-k3u1fbpfcp-watermark.image)

进入gitlab-runner容器

```shell
docker exec -it container-id bash

gitlab-runner register
```

按照步骤配置 url, token, tag, executor, executor先选择shell, 但docker更好

刷新runner页面, 绿点表示配置成功

![image.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/526b76268a444705ad4ad6d76f08cb49~tplv-k3u1fbpfcp-watermark.image)

### 新建一个vue项目

```shell
vue create hello-world

cd hello-world
git remote add origin http://your host ip/root/hello-world.git
git push -u origin --all
git push -u origin --tags
```

### 添加.gitlab-ci.yml

```yml
stages: # 分段
  - install
  - eslint
  - build
  - deploy

cache: # 缓存
  paths:
    - node_modules
    - dist

install-job:
  tags:
    - test
  stage: install
  script:
    - npm install

eslint-job:
  tags:
    - test
  stage: eslint
  script:
    - npm run lint

build-job:
  tags:
    - test
  stage: build
  script:
    - npm run build

deploy-job:
  tags:
    - test
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - sshpass -p $PASSWORD scp -r ./dist/* $CUSTOM_USERNAME@$CUSTOM_IP:/var/www/html
```

cache字段的paths表示全局缓存的目录, 在各个job中共享, 不会被删除

$开头的Variables可以在gitlab CI/CD中进行配置, 用来配置一些隐私信息: 

![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/4097ad0b8553443b838d8179e91ce940~tplv-k3u1fbpfcp-watermark.image)

因为我们的executor选择的是shell, 所以构建所需要的工具都需要现在host中准备好.

### 安装sshpass, nodejs
因为不能进入交互模式, 所以用sshpass直接指定密码

进入gitlab-runner容器

```shell
apt-get install sshpass nodejs npm
```

为了方便, 我们直接在在docker宿主机中安装nginx当作web服务器, 将打包后的vue项目部署过来

安装nginx, 因为80端口被gitlab占用, 我们部署在8080端口上

修改/etc/nginx/nginx.conf, 在http下添加

```conf
server {
    listen 8080;
    location / {
        root /var/www/html;
        index index.html;
    }
}
```

同时注释掉80端口
```nginx
# include /etc/nginx/sites-enabled/*;
```

启动nginx 
```shell
systemctl start nginx
```

同时给/etc/www/html 添加写权限

nginx成功启动的话, 可以进行第一次代码的push了. 接下来就会自动触发gitlab-ci/cd, 自动打包构建部署.

![image.png](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/da3fd892ab0544279e02cfdbc8973a83~tplv-k3u1fbpfcp-watermark.image)

浏览器输入ip+端口:

![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b891f1eabfeb4be1812b57b388fe3452~tplv-k3u1fbpfcp-watermark.image)

成功!

修改一下src/App.vue

```vue
<HelloWorld msg="Hello Gitlab CI/CD"/>
```

提交然后push, 等待构建, 第二次会很快.

![image.png](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/20d49896d9b84b6499d5e0730d2f509a~tplv-k3u1fbpfcp-watermark.image)

Bingo!

## executor选择docker

待填坑...
